language: php
php:
  - 5.5
  - 5.4
  - 5.3
before_script:
  - echo 'date.timezone = "Europe/Madrid"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install
script: php vendor/bin/phing